FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm config set proxy "http://inban1b-proxy.apac.nsn-net.net:8080/"
RUN npm config set https-proxy "http://inban1b-proxy.apac.nsn-net.net:8080/"
RUN npm config set registry https://registry.npmjs.org/

RUN npm install

COPY . .

CMD ["npm" , "run", "start"]